version: "3.7"

services:
  jobs-database-test:
    image: postgres:13
    restart: always
    networks:
      - jobs-ms-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: JobOffers-test
    healthcheck:
      test: pg_isready -U postgres -d JobOffers-test
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 5432

  jobs-server-test:
    build:
      dockerfile: Dockerfile.test
      context: .
    networks:
      - jobs-ms-test
      - network-for-ms
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: jobs-database-test
      DATABASE_SCHEMA: JobOffers-test
      DATABASE_PORT: 5432
      SERVER_PORT: 9093
      AMQP_SERVER_URL: amqp://guest:guest@rabbitmq:5673/
      AUTH0_DOMAIN: ten-test.eu.auth0.com
      AUTH0_CLIENT_ID: VEoiS6gjRN5S5wdm4qKqgphWh5rHp420
      AUTH0_CLIENT_SECRET: 6hJj_WWJwHQ8bQEua_cTEOk1p6_k4SQBeqfQBGCjGWfvExsaQYjweF-OHqARfKZL
      AUTH0_AUDIENCE: https://ten-test.eu.auth0.com/api/v2/
    ports:
      - "9099:9099"
    depends_on:
      jobs-database-test:
        condition: service_healthy

networks:
  jobs-ms-test:
    name: jobs-ms-test
    driver: bridge
  network-for-ms:
    name: network-for-ms
