version: "3.7"

services:
  database-jobs:
    image: postgres:13
    restart: always
    networks:
      - jobs-ms
      - network-for-ms
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "5436:5432"
    volumes:
      - data:/var/lib/postgresql/data

  jobs-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-run}
    restart: on-failure
    networks:
      - jobs-ms
      - network-for-ms
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_PORT: ${DATABASE_PORT}
      SERVER_PORT: ${SERVER_PORT}
      EVENTS_MS: ${EVENTS_MS}
    ports:
      - "9099:9099"
    depends_on:
      database-jobs:
        condition: service_healthy
    volumes:
      - logs:/root/logs

  promtail:
    image: grafana/promtail:latest
    networks:
      - jobs-ms
      - network-for-ms
    volumes:
      - "./promtail:/etc/promtail"
      - "/var/log:/var/log"
      - logs:/var/logs
    command: -config.file=/etc/promtail/promtail.yml
    restart: always

volumes:
  data:
    name: jobs-ms-database
  logs:
    name: jobs-logs

networks:
  jobs-ms:
    name: jobs-ms
    driver: bridge
  network-for-ms:
    name: network-for-ms
