version: "3.7"

services:
  jobs-database-test:
    image: postgres:13
    restart: always
    networks:
      - jobs-ms-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: JobOffers-tests
    healthcheck:
      test: pg_isready -U postgres -d JobOffers-tests
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 5432

  jobs-server-test:
    build:
      dockerfile: Dockerfile.test
      context: .
    networks:
      - jobs-ms-test
      - network-for-ms
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: jobs-database-test
      DATABASE_SCHEMA: JobOffers-tests
      DATABASE_PORT: 5432
      SERVER_PORT: 9099
      EVENTS_MS: http://localhost:9081/events
    ports:
      - "9099:9099"
    depends_on:
      jobs-database-test:
        condition: service_healthy

  database-events-test:
    image: postgres:13
    restart: always
    networks:
      - events-ms
      - network-for-ms
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SystemEvents-test
    healthcheck:
      test: pg_isready -U postgres -d SystemEvents-test
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "5451:5432"

  events-server:
    build:
      context: 'https://github.com/DevOps-Tim9/events-ms.git#develop'
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - events-ms
      - network-for-ms
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: database-events-test
      DATABASE_SCHEMA: SystemEvents-test
      DATABASE_PORT: 5432
      SERVER_PORT: 9081
    ports:
      - "9081:9081"
    depends_on:
      database-events-test:
        condition: service_healthy

networks:
  events-ms:
    name: events-ms
    driver: bridge
  jobs-ms-test:
    name: jobs-ms-test
    driver: bridge
  network-for-ms:
    name: network-for-ms
